### ISSUE TITLE
[TASK LIST] remote pong - frontend

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#100]
### Task completion criteria

- [x] 홈 페이지(/home)에서 '1 : 1' 버튼을 누르면 one-vs-one 모드로 원격 pong 게임을 진행할 수 있어야 합니다.
- [x] 홈 페이지(/home)에서 '토너먼트' 버튼을 누르면 tournament 모드로 원격 pong 게임을 진행할 수 있어야 합니다.
- [x] 원격 pong 게임 페이지에 접속하면 pong 웹소켓 서버로 연결을 시도해야 합니다.
- [x] 연결에 실패할 경우 오류 메시지를 toast로 표시해야 합니다.
- [x] 원격 pong 게임 페이지에서 네비게이션 바의 링크를 누르거나 뒤로 가기를 시도할 경우 경고 창을 띄워야 합니다.
- [x] Discussions에 정의한 문법에 따라 서버와 적절히 데이터를 주고 받아야 합니다.
- [x] 서버로부터 받은 데이터에 따라 pong 게임 화면을 적절히 그려야 합니다.
