### ISSUE TITLE
[TASK LIST] server-side pong

### ISSUE THREAD

**Issue by JoonhoLeecs** [organization-for-practice/PONG_PONG#103]
### Task completion criteria

- [ ] handshaking 과정에서 권한이 없는 요청을 거절해야 합니다
- [ ] game_type에 따라 새로 방을 생성하거나 모집중인 방에 자동으로 배정되어야 합니다.
- [ ] 모집중인 방은 대기인원이 변할때마다 대기인원 수를 알려줍니다.
- [ ] 모집이 끝난 방에서 pong game을 정상적으로 플레이할 수 있어야합니다.
- [ ] 플레이 중인 방에서 유저가 나갔을 때 게임 상태를 요구에 맞게 업데이트 해야합니다.
- [ ] 유저가 플레이중인 방에서 컨트롤할 차례고 일정시간 움직임이 없으면 접속을 종료해야 합니다.
- [ ] 모든 게임이 끝나고 일정 시간이 지나면 웹소켓 연결을 종료해야합니다.
- [ ] 게임 기록이 데이터베이스에 정상적으로 저장되야 합니다.

### Document

https://github.com/organization-for-practice/PONG_PONG/discussions/99

**Comment by JoonhoLeecs** [comment]
commit amend, push -f 여파로 이 브랜치는 머지 없이 닫고 109번으로 머지합니다.
