### ISSUE TITLE
[TASK LIST] pagination on profile page - game record

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#105]
### Task completion criteria

- [ ] 프로필 페이지의 '최근 전적'을 '전적'으로 수정합니다.
- [ ] 기본적으로 최근 5개의 게임 기록(1 페이지)을 표시합니다.
- [ ] 페이지 이동 버튼을 누르면 해당 페이지의 게임 기록들을 표시합니다.

**Comment by hijkl2e** [comment]
#115 에서 처리합니다
