### ISSUE TITLE
[TASK LIST] refresh waiting queue and refactor

### ISSUE THREAD

**Issue by JoonhoLeecs** [organization-for-practice/PONG_PONG#111]
### Task completion criteria

- [ ] 코드 변경으로 게임 백엔드 서버가 재시작하는 경우에도 이전 대기중인 사용자가 재접속시 중복접속 오류가 발생하지 않아야 합니다.
- [ ] websocket 연결 후 클라이언트에서 입력받는 값이 유효한지 검사해야 합니다
- [ ] 어제 수정사항으로 더 이상 불필요한 로직을 리팩토링합니다
