### ISSUE TITLE
[TASK LIST] profile page reconstruction

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#115]
### Task completion criteria

- [x] '1 : 1 전적' 또는 '토너먼트 전적' 버튼을 누르면 해당하는 전적을 표시해야 하며 기본 값은 '1 : 1 전적'입니다.
- [x] 기본적으로 10개의 전적을 표시하며 페이지 이동 버튼으로 다음 페이지 또는 이전 페이지로 이동할 수 있어야 합니다.
- [x] 1 : 1 전적은 일시, 상대, 점수, 결과(승리/패배)를 표시합니다.
- [x] 토너먼트 전적은 일시, 예선 상대, 예선 결과, 결승 상대, 결승 결과를 표시합니다.
- [x] 토너먼트에서 결승에 진출하지 못한 경우 결승 상대와 결승 결과는 '-'로 표시합니다.
- [x] 결과 버튼을 누르면 게임 상세 페이지로 이동합니다.
- [x] 전적이 존재하지 않더라도 '전적 없음' 텍스트를 표시하지 않습니다.
