### ISSUE TITLE
[TASK LIST] tournament details page

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#119]
### Task completion criteria

- [x] 기존 게임 상세 페이지와 유사한 형태로 토너먼트 상세 페이지를 만듭니다.
- [x] 페이지 상단에는 '#\1', '#\2', '#Final' 버튼을 배치합니다('\\' 제외).
- [x] 버튼을 누를 경우 url에 fragment(ex: '#Final)가 추가되며 해당하는 개별 게임의 기록을 표시해야 합니다.
- [x] '0 : 0'으로 끝난 게임은 차트를 표시하지 않습니다.
