### ISSUE TITLE
[TASK LIST] api updates

### ISSUE THREAD

**Issue by JoonhoLeecs** [organization-for-practice/PONG_PONG#124]
### Task completion criteria

- [ ] user_backend/api 에서 전달되는 정보를 깃북에 맞게 수정합니다.
- [ ] game_backend/api 에서 전달되는 정보를 깃북에 맞게 수정합니다.
- [ ] game_backend model, serializer를 수정합니다.
- [ ] game 종료시 게임 기록이 정확히 저장됩니다.

### Document

https://app.gitbook.com/o/zMIGgP1VIJQme7mSHZ4r/s/c9Ok0ZQtp6UiuC2KKRTl/group-1/user_backend-api
