### ISSUE TITLE
[BUG] friend error code

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/PONG_PONG#125]
### What happened?

_no_

### Task completion criteria

- [ ] friend 관련 api의 error code를 적절하게 전달해야 합니다.
- [ ] friend 관련 api의 error message가 구체적이여야 합니다.
- [ ] error message에 '.'가 없어야 합니다.
