### ISSUE TITLE
[TASK LIST] Tournament update/fix

### ISSUE THREAD

**Issue by JoonhoLeecs** [organization-for-practice/PONG_PONG#136]
### Task completion criteria

- [ ] winner pending 이후 tournament winner 전송
- [ ] tournament api 작동 안하는지 체크
- [ ] 확인되지 않은 tournament 중간에 접속종료
