### ISSUE TITLE
[TASK LIST] test user creation

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/PONG_PONG#150]
### Task completion criteria

- [ ] /auth/test?id=<test_user_id> link로 접근하면 test user로 로그인이 가능합니다.
- [ ] 기존에 존재지 않는 user는 새로 creation합니다.
- [ ] test_user_id는 test user를 구분하기 위한 용도로 사용될 뿐, user id 와 무관합니다.
