### ISSUE TITLE
[TASK LIST] https and deployment update

### ISSUE THREAD

**Issue by JoonhoLeecs** [organization-for-practice/PONG_PONG#161]
### Task completion criteria

- [ ] 프론트엔드, 백엔드 모두 https로 접속할 수 있어야 합니다
- [ ] websocket 접속시 wss로 업그레이드 가능해야 합니다
- [ ] docker container들이 의존성 순서에 맞춰 실행되어야 합니다.
- [ ] 기타 더이상 사용하지 않는 개발단계 세팅을 정리합니다.
