### ISSUE TITLE
[TASK LIST] 게임 매칭 화면

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#30]
### Task completion criteria

- [ ] local 연습 모드가 가능해야 합니다.
- [ ] 1:1 매칭이 가능해야 합니다.
- [ ] 4인 토너먼트가 가능해야 합니다.

### Document

_나중에 추가 예정_
