### ISSUE TITLE
[TASK LIST] user backend

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/PONG_PONG#33]
### Task completion criteria

- [x] jwt가 구현되어있어야 합니다.
- [x] 유저의 온라인 오프라인 여부를 확인할 수 있어야 합니다.
- [x] SQL injections/XSS 로부터 보호되어야 합니다.
- [x] 유저는 unique한 이름을 가져야 합니다.
- [x] 유저는 정보를 수정할 수 있습니다.
- [x] 유저는 아바타 사진을 업로드 할 수 있습니다.
- [x] 유저는 친구를 추가할 수 있습니다.
- [x] 42 인증이 가능해야 합니다.
- [x] 2FA로 인증후, jwt 토큰이 발급되어야 합니다.

### Document

_no_
