### ISSUE TITLE
[TASK LIST] Create frontend pages

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#36]
### Task completion criteria

- [x] 메인 페이지(/)가 있어야 합니다.
- [x] 메인 페이지에는 '42 계정으로 로그인' 버튼이 있으며 42 계정으로 원격 인증이 가능해야 합니다.
- [x] 홈 페이지(/home)가 있어야 합니다.
- [x] 홈 페이지에는 게임 모드별로 게임 플레이 페이지로 이동하는 버튼이 있어야 합니다.
- [x] 프로필 페이지(/profile/:nick)가 있어야 합니다.
- [x] 프로필 페이지에서는 닉네임, 아바타(프로필 사진), 접속 상태(온라인/오프라인), 전적 통계, 최근 전적을 제공해야 합니다.
- [x] 다른 유저의 프로필 페이지에 접속하면 해당 유저를 친구로 추가하거나 친구 목록에서 삭제할 수 있어야 합니다.
- [x] 게임 상세 페이지(/games/:id)가 있어야 합니다.
- [x] 프로필 페이지의 최근 전적 요소를 클릭하면 게임 상세 페이지로 이동해야 합니다.
- [x] 게임 상세 페이지에서는 각 게임의 세부적인 통계를 제공해야 합니다.
- [x] 친구 페이지(/friends)가 있어야 합니다.
- [x] 친구 페이지에서는 현재 유저의 친구 목록을 보여주며 닉네임을 클릭할 시 해당 유저의 프로필 페이지로 이동해야 합니다.
- [x] 설정 페이지(/settings)가 있어야 합니다.
- [x] 설정 페이지에서는 프로필 이미지 변경, 닉네임 변경, 로그아웃 기능을 제공해야 합니다.

### Document

_no_
