### ISSUE TITLE
[TASK LIST] local pong game

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#48]
### Task completion criteria

- [x] 로컬 퐁 게임 페이지(/pong/practice)가 있어야 합니다.
- [x] 홈 페이지(/)에서 '연습 모드' 버튼을 누르면 로컬 퐁 게임 페이지로 이동해야 합니다.
- [x] 'W' 키와 'S' 키로 왼쪽 패들을 조작할 수 있어야 합니다.
- [x] 'I' 키와 'K' 키로 오른쪽 패들을 조작할 수 있어야 합니다.
- [x] 공은 적절히 반사되어야 합니다.
- [x] 누구든지 먼저 5점을 획득하면 게임이 종료되어야 합니다.
- [x] 로컬 퐁 게임 페이지에서 벗어나면 모든 이벤트 리스너 함수를 제거하고 실시간 렌더링을 중단해야 합니다.

### Document

_no_
