### ISSUE TITLE
[TASK LIST] game history

### ISSUE THREAD

**Issue by JoonhoLeecs** [organization-for-practice/PONG_PONG#58]
### Task completion criteria

- [x]  user_backend가 /api/users/<:username>, /api/users/<:username>/ 에 해당하는 유저의 win, lose, recent_games요청할 수 있는 api endpoint 구현: Get /api/games?userId=1,2,3,4
- [x] /api/games에 요청시 모든 게임 반환
- [x] /api/games/:id에 요청시 개별 게임 기록를 응답
- [x] POST /api/games 지정된 형식으로 입력시 새로운 게임 기록 생성
- [x] POST에 지정된 형식을 필요시 수정
- [x] game_backend에서 토큰 유효성 검사로 사용자 확인
- [x] using /api/me? -> inheritant problem of jwt, conclude to dismiss
- [x] cross db transaction

### Document

POST body format
```
{
	  "type": string, only "One vs One" or "Tournament"
	  "played": datetime,
	  "first_player_id": int,
	  "second_player_id": int,
	  "winner": string, only accept "1" or "2"
	  "rally": string, max length 20, consist of '1' or '2'
}
```

Example:

```
{
	  "type": "One vs One",
	  "played": "2024-02-23T10:34:52.987087Z",
	  "first_player_id": 1,
	  "second_player_id": 2,
	  "winner": "1",
	  "rally": "112212121221212"
}
```

```
{
	  "type": "Tournament",
	  "played": "2024-02-24T11:30:00.000000Z",
	  "first_player_id": 3,
	  "second_player_id": 2,
	  "winner": "2",
	  "rally": "1112221212111222"
}
```
