### ISSUE TITLE
[TASK LIST] CLI program

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#64]
### Task completion criteria

- [x] CLI 프로그램에서 42 OAuth 로그인이 가능해야 합니다.
- [x] 2단계 인증을 설정한 사용자는 2단계 인증을 수행할 수 있어야 합니다.
- [x] token은 적절히 refresh 되어야 합니다.
- [x] 1 : 1 모드로 게임 플레이가 가능해야 합니다.
- [x] 토너먼트 모드로 게임 플레이가 가능해야 합니다.
