### ISSUE TITLE
[TASK LIST] Update friends page - remove recent game, add avatar and record

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#71]
### Task completion criteria

- [x] 친구 페이지(/friends)는 더 이상 최근 게임 기록을 보여주지 않습니다.
- [x] 친구 페이지(/friends)에서 사용자 이름 왼쪽에 아바타를 보여줍니다.
- [x] 친구 페이지(/friends)에서 기존의 최근 게임 기록 자리(맨 오른쪽)에 전적(N전 W승 L패)을 보여줍니다.
