### ISSUE TITLE
[TASK LIST] Update game button ui on home page

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#72]
### Task completion criteria

- [ ] 홈 페이지(/home)의 게임 버튼에 배경을 추가합니다.
- [ ] '연습 모드' 버튼의 배경은 Gam 배경으로 합니다(논의 필요).
- [ ] '1 : 1' 버튼의 배경은 Gun 배경으로 합니다(논의 필요).
- [ ] '토너먼트' 버튼의 배경은 Lee 배경으로 합니다(논의 필요).
