### ISSUE TITLE
[BUG] ui is broken when browser width is small and wrong chart font

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#94]
### What happened?

브라우저의 너비가 작을 때, 친구 페이지의 테이블이 비정상적으로 보이며, 설정 페이지의 사용자 이름 입력 칸이 너무 작게 보입니다.
또한 차트에는 폰트가 적용되지 않았습니다.

### Task completion criteria

- [ ] 브라우저의 너비와 상관 없이 친구 페이지의 테이블은 동일한 형태를 유지해야 합니다.
- [ ] 브라우저의 너비와 상관 없이 설정 페이지의 사용자 이름 입력 칸은 적절한 크기로 보여야 합니다.
- [ ] 차트에 Neo둥근모 폰트가 적용되어야 합니다.
