### ISSUE TITLE
[TASK LIST] improve profile link ui

### ISSUE THREAD

**Issue by hijkl2e** [organization-for-practice/PONG_PONG#96]
### Task completion criteria

- [ ] 프로필 페이지로 이동하는 링크의 폰트는 일반 폰트의 굵기와 동일합니다(게임 상세 페이지는 예외).
- [ ] 프로필 페이지로 이동하는 링크에 밑줄을 표시합니다.
- [ ] 게임 상세 페이지에서 플레이어의 사용자 이름을 클릭할 시 해당 사용자의 프로필 페이지로 이동합니다.
