### ISSUE TITLE
[TASK LIST] Store the score of a tournament in the Blockchain

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/PONG_PONG#98]
### Task completion criteria

- [ ] testing blockchain environment을 구축해야 합니다.
- [ ] testing environment는 etherium 기반, solidity로 compile 되는 smart contract를 보유하고 있습니다.
- [ ] testing blockchain environemnt는 tournament의 정보를 기록하고 있어야 합니다.
- [ ] smart contract는 유효하지 않은 값을 처리할 수 있어야 합니다.
- [ ] 오직 관리자 (django backend server 계정)만이 block chain에 기록을 등록할 수 있어야 합니다.
